### ISSUE TITLE
Error when working offline

### ISSUE THREAD

**Issue by fredrikaverpil** [pkgxdev/pkgx#1024]
When I enter a directory where `dev` has been activated, and when working offline:

```bash
$ cd dotfiles
resolving graph…error: Uncaught (in promise) TypeError: error sending request for url (https://dist.pkgx.dev/info-zip.org/unzip/darwin/aarch64/versions.txt): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known
    at async mainFetch (ext:deno_fetch/26_fetch.js:170:12)
    at async fetch (ext:deno_fetch/26_fetch.js:391:7)
    at async Object.get (https://deno.land/x/libpkgx@v0.17.0/src/hooks/useInventory.ts:17:15)
    at async Object.select (https://deno.land/x/libpkgx@v0.17.0/src/hooks/useInventory.ts:7:20)
```

Is this expected?

**Comment by jhheider** [comment]
Some care has been taken that existing installs should work when offline. However, I don't know off-hand if that same level of offline-capability applies to some of the newer/fancier features like automatic dev management. Did you already have `info-zip.org/unzip` installed? It should prefer a local version which satisfies its requirements where possible, but building the available version list does require the internet.

**Comment by fredrikaverpil** [comment]
No, I didn't have`info-zip.org/unzip` installed, and it also did not download once I got online... or at least there's no `info-zip.org` folder in `~/.pkgx`.

**Comment by fredrikaverpil** [comment]
Feel free to close this issue if this was expected @jhheider

**Comment by jhheider** [comment]
Ooh, that is odd. I know it's used internally for unpacking zip files, but if it needed it, I'd expect it to have been downloaded. Just to be clear, you re-entered the dev environment (`cd ~; cd -` or similar) after coming online?

**Comment by fredrikaverpil** [comment]
Yeah, after coming back online I've entered several directories with `dev` enabled.

**Comment by mxcl** [comment]
Yeah this shouldn't happen, let me think about why it might have.
