### ISSUE TITLE
attempt to write a readonly database

### ISSUE THREAD

**Issue by eifr** [pkgxdev/pkgx#1035]
after updating to `1.2.0` im getting this error for whaterver im trying to run:
```bash
➜  ~ pkgx deno --version
× unexpected error attempt to write a readonly database
│ Error: attempt to write a readonly database
│     at unwrap (https://deno.land/x/libpkgx@v0.19.0/vendor/sqlite3@0.10.0/src/util.ts:27:11)
│     at new Statement (https://deno.land/x/libpkgx@v0.19.0/vendor/sqlite3@0.10.0/src/statement.ts:110:5)
│     at Database.prepare (https://deno.land/x/libpkgx@v0.19.0/vendor/sqlite3@0.10.0/src/database.ts:138:12)
│     at Database.sql (https://deno.land/x/libpkgx@v0.19.0/vendor/sqlite3@0.10.0/src/database.ts:185:23)
│     at provides (https://deno.land/x/libpkgx@v0.19.0/src/hooks/useSyncCache.ts:84:18)
│     at eventLoopTick (ext:core/01_core.js:168:7)
│     at async _which (https://deno.land/x/libpkgx@v0.19.0/src/plumbing/which.ts:31:20)
│     at async which (https://deno.land/x/libpkgx@v0.19.0/src/plumbing/which.ts:10:20)
│     at async default (file:///tmp/deno-compile-pkgx/pkgx/src/prefab/resolve-arg0.ts:7:14)
│     at async find_arg0 (file:///tmp/deno-compile-pkgx/pkgx/src/modes/x.ts:96:15)
╰─➤ https://github.com/pkgxdev/pkgx/issues/new
```

**Comment by eifr** [comment]
Works again after uninstall and reinstall :)

**Comment by mxcl** [comment]
Thanks for the heads up, we'll monitor. Nothing occurs for why this would happen currently, especially since reinstall worked unexpectedly.

**Comment by tekhnus** [comment]
For me it started happening right after I interrupted an installation with Ctrl+C

**Comment by sporkd** [comment]
Just started experiencing this as well. Can fix with `pkgx --sync` but it keeps coming back from time to time.

**Comment by mxcl** [comment]
I have yet to experience it. If I do I'll be able to figure it out. Until then I’ll keep noodling.

**Comment by clanghans** [comment]
currently experience the same thing with a slightly different log message in pkgx version `1.2.1`

```sh
❯ dev
× unexpected error attempt to write a readonly database
│ Error: attempt to write a readonly database
│     at unwrap (https://deno.land/x/libpkgx@v0.19.0/vendor/sqlite3@0.10.0/src/util.ts:27:11)
│     at new Statement (https://deno.land/x/libpkgx@v0.19.0/vendor/sqlite3@0.10.0/src/statement.ts:110:5)
│     at Database.prepare (https://deno.land/x/libpkgx@v0.19.0/vendor/sqlite3@0.10.0/src/database.ts:138:12)
│     at Database.sql (https://deno.land/x/libpkgx@v0.19.0/vendor/sqlite3@0.10.0/src/database.ts:185:23)
│     at companions (https://deno.land/x/libpkgx@v0.19.0/src/hooks/useSyncCache.ts:119:18)
│     at eventLoopTick (ext:core/01_core.js:168:7)
│     at async Object.companions (https://deno.land/x/libpkgx@v0.19.0/src/hooks/usePantry.ts:72:16)
│     at async Promise.all (index 0)
│     at async default (file:///tmp/deno-compile-pkgx/pkgx/src/prefab/install.ts:9:25)
│     at async default (file:///tmp/deno-compile-pkgx/pkgx/src/modes/internal.activate.ts:26:25)
``` 

a `pkgx --sync` seemed to fix it. We'll see for how long

**Comment by clanghans** [comment]
I can reproduce the issue now. It happens when I request a package which is not existing and canceling the process mit syncing. 
After deleting the ~/.pkgx directory the issue is gone. 
Log is attached.

[log.txt](https://github.com/user-attachments/files/17164373/log.txt)

**Comment by mxcl** [comment]
Unfortunately I cannot reproduce, but this does give me ammunition to try and figure it out. Thanks.,

**Comment by clanghans** [comment]
> Unfortunately I cannot reproduce, but this does give me ammunition to try and figure it out. Thanks.,

You are on Mac, right? Is the cleanup/signal handling different then on Linux?

**Comment by mxcl** [comment]
No longer applies to pkgx^2
