### ISSUE TITLE
Cloudflare WARP SSL issues

### ISSUE THREAD

**Issue by jay-steyn** [pkgxdev/pkgx#1046]
We are running behind Cloudflare warp. Its a real pain that we have to install their certificates locally for things to work.
Running either `dev` or `pkgx` (latest versions on Mac) produced the following error:

```
× unexpected error client error (Connect)
│ TypeError: client error (Connect)
│     at async mainFetch (ext:deno_fetch/26_fetch.js:170:12)
│     at async fetch (ext:deno_fetch/26_fetch.js:391:7)
│     at async the_meat (https://deno.land/x/libpkgx@v0.19.1/src/hooks/useDownload.ts:96:15)
│     at async Object.download (https://deno.land/x/libpkgx@v0.19.1/src/hooks/useDownload.ts:25:25)
│     at async Object.sync (https://deno.land/x/libpkgx@v0.19.1/src/hooks/useSync.ts:57:5)
│     at async default (https://deno.land/x/libpkgx@v0.19.1/src/hooks/useSync.ts:15:5)
│     at async ensure_pantry (file:///var/folders/xq/vgsymdvs5dz687mdx4sq74_c0000gp/T/deno-compile-pkgx/pkgx/src/app.ts:160:5)
│     at async default (file:///var/folders/xq/vgsymdvs5dz687mdx4sq74_c0000gp/T/deno-compile-pkgx/pkgx/src/app.ts:129:9)
│     at async file:///var/folders/xq/vgsymdvs5dz687mdx4sq74_c0000gp/T/deno-compile-pkgx/pkgx/entrypoint.ts:59:3
```

Anyway to attach the cert required?

**Comment by mxcl** [comment]
pkgx^2 is a rewrite and uses the system keychain (on macOS) and openssl (on Linux) so it should be possible to fix this with ^2. (^1 probs just required setting `$DENO_SSL_CERTFILE`).

With openSSL setting `$SSL_CERT_FILE` should work. On macOS you can add custom certs to the keychain.

If there is an established way we should allow you to add custom certs we’re open to it.
