### ISSUE TITLE
Xcodeproj - PermissionDenied

### ISSUE THREAD

**Issue by waliid** [pkgxdev/pkgx#1050]
Hi there,

I'm trying to use the `xcodeproj` package that I created previously, and I encountered the following error:
 
```sh
pkgx xcodeproj
 ✓  ~/.pkgx/cocoapods.org/xcodeproj/v1.27.0                          
× unexpected error                                                   
│ PermissionDenied
│     at default (file:///var/folders/zl/2tf3qmpd0wq4zkn_thg3dynm0000gn/T/deno-compile-pkgx/pkgx/src/utils/execve.ts:30:15)
│     at default (file:///var/folders/zl/2tf3qmpd0wq4zkn_thg3dynm0000gn/T/deno-compile-pkgx/pkgx/src/modes/x.ts:40:3)
│     at eventLoopTick (ext:core/01_core.js:175:7)
│     at async default (file:///var/folders/zl/2tf3qmpd0wq4zkn_thg3dynm0000gn/T/deno-compile-pkgx/pkgx/src/app.ts:60:11)
│     at async file:///var/folders/zl/2tf3qmpd0wq4zkn_thg3dynm0000gn/T/deno-compile-pkgx/pkgx/entrypoint.ts:59:3

```

Any idea ?

**Comment by jhheider** [comment]
it's the missing shebang. adding `#!/bin/sh` to the top of the prop fixes it. i'll update pantry.

**Comment by jhheider** [comment]
https://github.com/pkgxdev/pantry/actions/runs/11977122568

**Comment by waliid** [comment]
Thanks @jhheider!
