### ISSUE TITLE
Incompatible dependencies on package vips

### ISSUE THREAD

**Issue by davireis** [pkgxdev/pkgx#1062]
When trying to use libvips.org it ends up with two incompatible versions, 14 and 13, of a given dependency. I was unable to determine the specific conflicting dependency. One line repro below.

Although it would be nice to fix vips, it would be even better to get a better error message such that I could fix/workaround the problem more easily.

```
docker run -i -t pkgxdev/pkgx:v1@sha256:ee3e4c59bd8b575765d5ab4234872bbe17434921ac47d4a0cc549218288aafba pkgx +libvips.org true
× unexpected error cannot intersect: ^14 && ^13
│ Error: cannot intersect: ^14 && ^13
│     at Module.intersect (https://deno.land/x/libpkgx@v0.20.1/src/utils/semver.ts:387:30)
│     at hydrate (https://deno.land/x/libpkgx@v0.20.1/src/plumbing/hydrate.ts:53:50)
│     at eventLoopTick (ext:core/01_core.js:175:7)
│     at async failsafe (file:///tmp/deno-compile-pkgx/pkgx/src/prefab/failsafe.ts:6:12)
│     at async default (file:///tmp/deno-compile-pkgx/pkgx/src/prefab/install.ts:10:41)
│     at async default (file:///tmp/deno-compile-pkgx/pkgx/src/modes/x.ts:31:18)
│     at async default (file:///tmp/deno-compile-pkgx/pkgx/src/app.ts:60:11)
│     at async file:///tmp/deno-compile-pkgx/pkgx/entrypoint.ts:59:3
╰─➤ https://github.com/pkgxdev/pkgx/issues/new
```

**Comment by jhheider** [comment]
Tracking the dependency source for errors would be good. You should be able to use `pkgx +libvips.org^13` to work around it in the short term (hopefully). Searching the pantry for `libvips.org` should help track it down pretty quickly.

I can take a look when I get a chance this week.

**Comment by jhheider** [comment]
looking into this, libheif is linked against libstdc++ 13 and poppler against 14. so, rebuilding libheif should fix this (but might cause other webs of issues). let me see what I can do.
