### ISSUE TITLE
tar failure error messages need improvement

### ISSUE THREAD

**Issue by icorbett** [pkgxdev/pkgx#619]
Trying out tea in the `teaxyz/cli` docker image:

tea $ python --version
downloading 803 KiB/s 0.63/4 MiB
tar: share/terminfo/d/d230-dg: Cannot hard link to 'share/terminfo/d/d230c-dg': No space left on device
tar: share/terminfo/d/d216-dg: Cannot hard link to 'share/terminfo/d/d217-dg': No space left on device
tar: share/terminfo/d/dm80w: Cannot hard link to 'share/terminfo/d/dt80w': No space left on device
tar: share/terminfo/d/dm2500: Cannot hard link to 'share/terminfo/d/datamedia2500': No space left on device
share/terminfo/t/tvi912b-p: Cannot hard link to 'share/terminfo/t/tvi912c-p': No space left on device
tar: share/terminfo/t/tvi912b-unk: Cannot hard link to 'share/terminfo/t/tvi912c-unk': No space left on device
tar: share/terminfo/t/tw52-color: Cannot hard link to 'share/terminfo/t/tw52': No space left on device
downloading 1.20 MiB/s 1.56/86 MiB
installed: ~/.tea/libexpat.github.io/v2.5.0
installed: ~/.tea/sourceware.org/libffi/v3.4.4
installed: ~/.tea/sourceware.org/bzip2/v1.0.8
installed: ~/.tea/bytereef.org/mpdecimal/v2.5.1
installed: ~/.tea/gnu.org/readline/v8.2.0
installed: ~/.tea/tukaani.org/xz/v5.4.3
installed: ~/.tea/sqlite.org/v3.42.0
installing 13% 2.11 MiB/s 12.2/90 MiB
installing 14% 2.11 MiB/s 12.2/90 MiB

panic: spilt tea. we’re sorry and we’ll fix it… but you have to report the bug!

    https://github.com/teaxyz/cli/issues/new?title=panic%3Atar+exited+with+status+2

----------------------------------------------------->> attachment begin
Error: tar exited with status 2
    at install (https://deno.land/x/libtea@v0.6.2/src/plumbing/install.ts:91:19)
    at eventLoopTick (ext:core/01_core.js:183:11)
    at async Promise.all (index 0)
    at async default (file:///tmp/465b484f/src/prefab/install.ts:63:27)
    at async default (file:///tmp/465b484f/src/prefab/setup.ts:84:38)
    at async run (file:///tmp/465b484f/src/app.main.ts:41:63)
    at async file:///tmp/465b484f/src/app.ts:20:5
<<----------------------------------------------------- attachment end

gzip: stdin: unexpected end of file

gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now

**Comment by mxcl** [comment]
```
No space left on device
```

is the container full or is the error spurious?

**Comment by icorbett** [comment]
Indeed this was very strange, I was still able to install several versions of `node` and `ruby` after the `python` error. Eventually, I started digging into my local docker engine and after pruning everything and removing several unneeded images I was still experiencing this same problem. Only after I removed some unnecessary volumes did this start working.

I am satisfied that this is not a problem with `tea` through troubleshooting it was not obvious for reasons I don't yet understand. Notably, I had a similar problem with `vim` at the same time as `python` but as mentioned before I was able to consume a couple hundred MB before looking outside the running container.

In any case, sorry for the noise, if this is not a useful issue feel free to close.

**Comment by mxcl** [comment]
I agree our errors suck, so will keep this open and change its tittle. I appreciate the report thank you.

**Comment by mxcl** [comment]
We no longer use external `tar`
