### ISSUE TITLE
Detect lack of internet

### ISSUE THREAD

**Issue by dcvz** [pkgxdev/pkgx#684]
ATM if you try to do any internet bound command line `tea -S` and there's no internet connection tea will report its usual error screen:

```
panic: spilt tea. we’re sorry and we’ll fix it… but you have to report the bug!
    https://github.com/teaxyz/cli/issues/new?title=panic%3Aerror+sending+request+for+url+(https%3A%2F%2Fgithub.com%2Fteaxyz%2Fpantry%2Farchive%2Frefs%2Fheads%2Fmain.tar.gz)%3A+error+trying+to+connect%3A+dns+error%3A+failed+to+lookup+address+information%3A+nodename+nor+servname+provided%2C+or+not+known

TypeError: error sending request for url (https://github.com/teaxyz/pantry/archive/refs/heads/main.tar.gz): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known
    at async mainFetch (ext:deno_fetch/26_fetch.js:266:12)
    at async fetch (ext:deno_fetch/26_fetch.js:490:7)
    ...
```

While any dev parsing this might easily realize what the issue is, it does invite the user to create an issue on Github. For a regular user it would save them and the tea team time by letting the user know the network is down and they should try again later.

**Comment by michaelessiet** [comment]
@jhheider would it be possible to catch lack of internet connection and display an appropriate error message?

**Comment by michaelessiet** [comment]
<img width="1186" alt="Screenshot 2023-12-28 at 21 18 38" src="https://github.com/pkgxdev/pkgx/assets/23281128/cb7ef6a3-9571-4b54-8e98-bd3cceb1eb48">
This is the error
