### ISSUE TITLE
panic:invalid absolute path: 

### ISSUE THREAD

**Issue by jennyriess** [pkgxdev/pkgx#760]
Error: invalid absolute path: 
    at new Path (https://deno.land/x/libtea@v0.10.7/src/utils/Path.ts:37:19)
    at the_meat (https://deno.land/x/libtea@v0.10.7/src/hooks/useDownload.ts:79:23)
    at Object.download (https://deno.land/x/libtea@v0.10.7/src/hooks/useDownload.ts:24:33)
    at fetch_it (file:///private/var/folders/y3/yr3bxsy95c3gfwwj61ytbp000000gq/T/a6868117/src/prefab/setup.ts:150:42)
    at default (file:///private/var/folders/y3/yr3bxsy95c3gfwwj61ytbp000000gq/T/a6868117/src/prefab/setup.ts:23:24)
    at run (file:///private/var/folders/y3/yr3bxsy95c3gfwwj61ytbp000000gq/T/a6868117/src/app.main.ts:44:69)
    at async file:///private/var/folders/y3/yr3bxsy95c3gfwwj61ytbp000000gq/T/a6868117/src/app.ts:23:5
<<------------------------------------------------------- attachment end
/dev/fd/12:2: no matches found: [-SEn]
/dev/fd/12:2: no matches found: [--]
Usage: file [-bcCdEhikLlNnprsSvzZ0] [--extension] [--mime-encoding]
            [--mime-type] [-e <testname>] [-F <separator>]  [-f <namefile>]
            [-m <magicfiles>] [-M magicfiles] [-P <parameter=value>] [--exclude-quiet]
            <file> ...
       file -C [-m <magicfiles>]
       file [--help]
Try `file --help' for more information.

panic: spilt tea. we’re sorry and we’ll fix it… but you have to report the bug!

    https://github.com/teaxyz/cli/issues/new?title=panic%3Ainvalid+absolute+path%3A+

**Comment by mxcl** [comment]
Sorry for this issue. What command did you run do you remember?

**Comment by mxcl** [comment]
The only call to `new Path` we have in useDownload uses the `pathname` property of a URL to create a new Path. ChatGPT insists pathname cannot be relative and the code we have that throws this error checks for falsiness or not starting with `/`.

Basically I cannot see how this error occurs. Can you provide more detail?
