### ISSUE TITLE
@latest not working in pkgx.yaml

### ISSUE THREAD

**Issue by svenjacobs** [pkgxdev/pkgx#797]
While I can use

```
❯ pkgx firebase@latest --version
12.6.2
```

when I declare my dependencies in `pkgx.yaml` like this

```yaml
dependencies:
    node@18 firebase@latest
```

I get the following error

```
× unexpected error invalid semver range: @latest
│ Error: invalid semver range: @latest
│     at err (https://deno.land/x/libpkgx@v0.14.1/src/utils/semver.ts:120:23)
│     at new Range (https://deno.land/x/libpkgx@v0.14.1/src/utils/semver.ts:209:49)
│     at parse (https://deno.land/x/libpkgx@v0.14.1/src/utils/pkg.ts:8:22)
│     at Array.map (<anonymous>)
│     at parse_deps (file:///Users/builder/actions-runner/_work/pkgx/pkgx/src/utils/devenv.ts:289:34)
│     at extract_well_formatted_entries (file:///Users/builder/actions-runner/_work/pkgx/pkgx/src/utils/devenv.ts:279:22)
│     at parse_well_formatted_node (file:///Users/builder/actions-runner/_work/pkgx/pkgx/src/utils/devenv.ts:250:24)
│     at default (file:///Users/builder/actions-runner/_work/pkgx/pkgx/src/utils/devenv.ts:102:17)
│     at eventLoopTick (ext:core/01_core.js:183:11)
│     at async default (file:///Users/builder/actions-runner/_work/pkgx/pkgx/src/modes/internal.activate.ts:16:34)
╰─➤ https://github.com/pkgxdev/pkgx/issues/new
```

when changing into the directory.

**Comment by mxcl** [comment]
hmm yeah, my bad this is indeed an omission.

I'm not sure I would recommend this though, it requires HTTP for every usage. `@latest` always checks our servers to ensure it is latest. This mirrors the behavior of other such tools.

`firebase` by itself means “latest that is already cached or latest if none”.

**Comment by svenjacobs** [comment]
I understand. Maybe there should be a descriptive error message or explanation when using `@latest` because currently it looks like a bug 🙂

**Comment by mxcl** [comment]
yes, it's a bug. It should either error informatively or work intuitively
