### ISSUE TITLE
`PermissionDenied` unexpecred error when running a Java file

### ISSUE THREAD

**Issue by alex-vit** [pkgxdev/pkgx#840]
Using `pkgx 1.1.0`. Unsure if bug or feature request:
Add or fix support for running single-file Java apps. ([JEP-330](https://openjdk.org/jeps/330))

Tested with a `PkgxTest.java`:
```java
class PkgxTest {
    public static void main(String[]args){
        System.out.println("Hello from plain Java file!");
    }
}
```

and got:
```
alex tmp % java PkgxTest.java
Hello from plain Java file!
alex tmp % pkgx PkgxTest.java
× unexpected error
│ PermissionDenied
│     at default (file:///Users/builder/actions-runner/_work/pkgx/pkgx/src/utils/execve.ts:19:15)
│     at default (file:///Users/builder/actions-runner/_work/pkgx/pkgx/src/modes/x.ts:39:3)
│     at eventLoopTick (ext:core/01_core.js:183:11)
│     at async default (file:///Users/builder/actions-runner/_work/pkgx/pkgx/src/app.ts:48:11)
│     at async file:///Users/builder/actions-runner/_work/pkgx/pkgx/entrypoint.ts:59:3
╰─➤ https://github.com/pkgxdev/pkgx/issues/new
alex tmp % 
```

P.S. pkgx is very cool! Keep on rockin.

**Comment by jhheider** [comment]
My guess is that, just like a shell, that java file needs execute permission to be run that way. Try chmod +x on it.

If that doesn't make it runnable, then we may need to add an interprets stanza to the openjdk package.

**Comment by alex-vit** [comment]
Trying `chmod +x` yields the same:
```
alex tmp % chmod +x PkgxTest.java 
alex tmp % pkgx PkgxTest.java
× unexpected error
│ PermissionDenied
│     at default (file:///Users/builder/actions-runner/_work/pkgx/pkgx/src/utils/execve.ts:19:15)
│     at default (file:///Users/builder/actions-runner/_work/pkgx/pkgx/src/modes/x.ts:39:3)
│     at eventLoopTick (ext:core/01_core.js:183:11)
│     at async default (file:///Users/builder/actions-runner/_work/pkgx/pkgx/src/app.ts:48:11)
│     at async file:///Users/builder/actions-runner/_work/pkgx/pkgx/entrypoint.ts:59:3
╰─➤ https://github.com/pkgxdev/pkgx/issues/new
alex tmp % 
```

Which is expected, I guess? I really liked how I can do `pkgx file.ts`, without setting `+x`, and have it resolve to and run `deno` immediately. 🪄  Was wondering why not do the same for Java.

**Comment by jhheider** [comment]
simple fix. `pkgx --sync` should get the updated pantry entry:
```shell
% pkgx PkgxTest.java
Hello from plain Java file!
```
