### ISSUE TITLE
Air Gapped packages install

### ISSUE THREAD

**Issue by mxcl** [pkgxdev/pkgx#854]
### Discussed in https://github.com/orgs/pkgxdev/discussions/853

<div type='discussions-op-text'>

<sup>Originally posted by **danielefiungo** November  9, 2023</sup>
Looking around I don't have find a way to install a package then turn off internet and call the installed package for the first time. 

```sh
 $ pkgx install kubectl   
pkgx: installed: ~/.local/bin/kubectl

```
 Disconnecting from internet ...

```
 $ kubectl
× unexpected error error sending request for url (https://dist.pkgx.dev/kubernetes.io/kubectl/linux/aarch64/versions.txt): error trying to connect: dns error: failed to lookup address information: Name or service not known
│ TypeError: error sending request for url (https://dist.pkgx.dev/kubernetes.io/kubectl/linux/aarch64/versions.txt): error trying to connect: dns error: failed to lookup address information: Name or service not known
│     at async mainFetch (ext:deno_fetch/26_fetch.js:277:12)
│     at async fetch (ext:deno_fetch/26_fetch.js:504:7)
│     at async Object.get (https://deno.land/x/libpkgx@v0.15.0/src/hooks/useInventory.ts:17:15)
│     at async Object.select (https://deno.land/x/libpkgx@v0.15.0/src/hooks/useInventory.ts:7:20)
│     at async Promise.all (index 0)
│     at async resolve (https://deno.land/x/libpkgx@v0.15.0/src/plumbing/resolve.ts:55:3)
│     at async default (file:///home/builder/actions-runner/_work/pkgx/pkgx/src/prefab/install.ts:11:51)
│     at async default (file:///home/builder/actions-runner/_work/pkgx/pkgx/src/modes/x.ts:30:18)
│     at async default (file:///home/builder/actions-runner/_work/pkgx/pkgx/src/app.ts:48:11)
│     at async file:///home/builder/actions-runner/_work/pkgx/pkgx/entrypoint.ts:59:3
╰─➤ https://github.com/pkgxdev/pkgx/issues/new
```

This can really be useful when you are building an image that later will not have full access to internet.
</div>

**Comment by mxcl** [comment]
This should be fine know with `pkgm`.
