### ISSUE TITLE
Error running: 'pkgx bpytop'

### ISSUE THREAD

**Issue by zvarnes** [pkgxdev/pkgx#879]
```
× unexpected error untar failed
│ Error: untar failed
│     at Object.default [as useSync] (https://deno.land/x/libpkgx@v0.15.0/src/hooks/useSync.ts:42:13)
│     at eventLoopTick (ext:core/01_core.js:183:11)
│     at async find_it (file:///Users/builder/actions-runner/_work/pkgx/pkgx/src/modes/x.ts:72:3)
│     at async default (file:///Users/builder/actions-runner/_work/pkgx/pkgx/src/modes/x.ts:16:17)
│     at async default (file:///Users/builder/actions-runner/_work/pkgx/pkgx/src/app.ts:48:11)
│     at async file:///Users/builder/actions-runner/_work/pkgx/pkgx/entrypoint.ts:59:3
```

**Comment by zvarnes** [comment]
No I didn't package it locally. I didn't know it wasn't packaged yet because I've only seen that error. This is what I get when running `pkgx --sync` 
```
× unexpected error untar failed
│ Error: untar failed
│     at default (https://deno.land/x/libpkgx@v0.15.0/src/hooks/useSync.ts:42:13)
│     at eventLoopTick (ext:core/01_core.js:183:11)
│     at async default (file:///Users/builder/actions-runner/_work/pkgx/pkgx/src/app.ts:27:7)
│     at async file:///Users/builder/actions-runner/_work/pkgx/pkgx/entrypoint.ts:59:3
╰─➤ https://github.com/pkgxdev/pkgx/issues/new
```

**Comment by jhheider** [comment]
interesting. it's possible something in your pkgx directory got created with root permissions, so you can't write to it. you probably want to run
```sh
$ sudo chown -R $(whoami) ~/.pkgx ~/Library/Application\ Support/pkgx ~/Library/Caches/pkgx
```
if you're on mac or
```sh
$ sudo chown -R $(whoami) ~/.pkgx ~/.local/share/pkgx ~/.local/cache/pkgx
```
if you're on linux.

i don't recommend running `pkgx` with `sudo`, unless you intend to only run it with `sudo`.

**Comment by zvarnes** [comment]
Yeah it was a permission issue after all. Must have done something stupid on install. Thank you!
