### ISSUE TITLE
can't use `dev` to install postgresql and nodejs at the same time

### ISSUE THREAD

**Issue by scottjg** [pkgxdev/pkgx#934]
```
scottjg@scottjgs-MacBook-Air rewatch % dev
× unexpected error cannot intersect: ^71 && ^73
│ Error: cannot intersect: ^71 && ^73
│     at Module.intersect (https://deno.land/x/libpkgx@v0.16.0/src/utils/semver.ts:384:30)
│     at hydrate (https://deno.land/x/libpkgx@v0.16.0/src/plumbing/hydrate.ts:51:48)
│     at eventLoopTick (ext:core/01_core.js:182:7)
│     at async failsafe (file:///Users/builder/actions-runner/_work/pkgx/pkgx/src/prefab/failsafe.ts:5:12)
│     at async default (file:///Users/builder/actions-runner/_work/pkgx/pkgx/src/prefab/install.ts:10:41)
│     at async default (file:///Users/builder/actions-runner/_work/pkgx/pkgx/src/modes/internal.activate.ts:26:25)
│     at async default (file:///Users/builder/actions-runner/_work/pkgx/pkgx/src/app.ts:78:35)
│     at async file:///Users/builder/actions-runner/_work/pkgx/pkgx/entrypoint.ts:59:3

```

```
scottjg@scottjgs-MacBook-Air rewatch % git diff
diff --git a/package.json b/package.json
index 51ec0d7d6..37bce14c2 100644
--- a/package.json
+++ b/package.json
@@ -52,6 +52,7 @@
     "yarn": "1.x"
   },
   "version": "0.1.0",
+  "pkgx": "opensearch@2.11 redis.io@6.2 postgresql.org",
   "devDependencies": {
     "@prettier/plugin-ruby": "^1.5.5",
     "@types/chartist": "^0.11.1",
```

**Comment by scottjg** [comment]
```
scottjg@scottjgs-MacBook-Air rewatch % pkgx --version
pkgx 1.1.5
```

**Comment by scottjg** [comment]
after digging in a little more, i see that the `node` package depends on `unicode.org@^71` while postgres depends on `unicode.org@^73`.  i am a little confused... since it would seem like you should be able to have each package depend on different versions of a library dependency?

easy to reproduce with:
```
scottjg@scottjgs-MacBook-Air ~ % pkgx +node +postgres
× unexpected error cannot intersect: ^71 && ^73
│ Error: cannot intersect: ^71 && ^73
│     at Module.intersect (https://deno.land/x/libpkgx@v0.16.0/src/utils/semver.ts:384:30)
│     at hydrate (https://deno.land/x/libpkgx@v0.16.0/src/plumbing/hydrate.ts:51:48)
│     at eventLoopTick (ext:core/01_core.js:182:7)
│     at async failsafe (file:///Users/builder/actions-runner/_work/pkgx/pkgx/src/prefab/failsafe.ts:5:12)
│     at async default (file:///Users/builder/actions-runner/_work/pkgx/pkgx/src/prefab/install.ts:10:41)
│     at async default (file:///Users/builder/actions-runner/_work/pkgx/pkgx/src/modes/env.ts:6:25)
│     at async default (file:///Users/builder/actions-runner/_work/pkgx/pkgx/src/app.ts:120:21)
│     at async file:///Users/builder/actions-runner/_work/pkgx/pkgx/entrypoint.ts:59:3
```

**Comment by scottjg** [comment]
i see this bug is explored/explained in https://github.com/pkgxdev/pantry/issues/4104

**Comment by mxcl** [comment]
Yeah I really gotta come up with a solution for this. Probably for now trying to standardize on the same unicode (^71) as much as possible will do.
