### ISSUE TITLE
`pkgx black`: PermissionError: [Errno 13] Permission denied: '/.git'

### ISSUE THREAD

**Issue by magnusviri** [pkgxdev/pkgx#973]
This happens on more than one of my computers. One is macOS 14, the other is macOS 13.

```
pkgx black            
 ✓  ~/.pkgx/python.org/v3.11.8                                    
Traceback (most recent call last):                                
  File "/Users/test/.pkgx/github.com/psf/black/v24.2.0/venv/bin/black", line 8, in <module>
    sys.exit(patched_main())
             ^^^^^^^^^^^^^^
  File "/Users/test/.pkgx/github.com/psf/black/v24.2.0/venv/lib/python3.11/site-packages/black/__init__.py", line 1587, in patched_main
    main()
  File "/Users/test/.pkgx/github.com/psf/black/v24.2.0/venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/test/.pkgx/github.com/psf/black/v24.2.0/venv/lib/python3.11/site-packages/click/core.py", line 1077, in main
    with self.make_context(prog_name, args, **extra) as ctx:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/test/.pkgx/github.com/psf/black/v24.2.0/venv/lib/python3.11/site-packages/click/core.py", line 943, in make_context
    self.parse_args(ctx, args)
  File "/Users/test/.pkgx/github.com/psf/black/v24.2.0/venv/lib/python3.11/site-packages/click/core.py", line 1408, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/test/.pkgx/github.com/psf/black/v24.2.0/venv/lib/python3.11/site-packages/click/core.py", line 2400, in handle_parse_result
    value = self.process_value(ctx, value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/test/.pkgx/github.com/psf/black/v24.2.0/venv/lib/python3.11/site-packages/click/core.py", line 2362, in process_value
    value = self.callback(ctx, self, value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/test/.pkgx/github.com/psf/black/v24.2.0/venv/lib/python3.11/site-packages/black/__init__.py", line 129, in read_pyproject_toml
    value = find_pyproject_toml(
            ^^^^^^^^^^^^^^^^^^^^
  File "/Users/test/.pkgx/github.com/psf/black/v24.2.0/venv/lib/python3.11/site-packages/black/files.py", line 109, in find_pyproject_toml
    path_project_root, _ = find_project_root(path_search_start, stdin_filename)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/test/.pkgx/github.com/psf/black/v24.2.0/venv/lib/python3.11/site-packages/black/files.py", line 91, in find_project_root
    if (directory / ".git").exists():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/test/.pkgx/python.org/v3.11.8/lib/python3.11/pathlib.py", line 1235, in exists
    self.stat()
  File "/Users/test/.pkgx/python.org/v3.11.8/lib/python3.11/pathlib.py", line 1013, in stat
    return os.stat(self, follow_symlinks=follow_symlinks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/.git'
```

**Comment by magnusviri** [comment]
Yeah, I just confirmed it's a black bug.
